#!/usr/bin/env bash
#
# Install my emacs setup
#

# Set environment
export PATH="$HOME/.cask/bin:$PATH"
cd ~/.emacs.d

# Install emacs
sudo apt-get install emacs

# Install packages for epdfinfo pdf-tools
sudo apt-get install libpng-dev libz-dev libpoppler-glib-dev libpoppler-private-dev

# Update submodule
git submodule init
git submodule update

# Install everything using cask
curl -fsSkL https://raw.github.com/cask/cask/master/go | python
cask install
