#!/usr/bin/env bash
#
# Install my emacs setup
#

# Set environment
export PATH="$HOME/.cask/bin:$PATH"
cd ~/.emacs.d

# Install emacs
sudo apt-get install emacs

# Install curl
sudo apt-get install curl

# Install packages for epdfinfo pdf-tools
sudo apt-get install libpng-dev libz-dev libpoppler-glib-dev libpoppler-private-dev gcc g++ make automake autoconf

# Install optional packages for exwm
sudo apt-get install volti udiskie numlockx redshift-gtk network-manager network-manager-gnome

# # Update submodule
# git submodule init
# git submodule update

# # Install everything using cask
# curl -fsSkL https://raw.github.com/cask/cask/master/go | python
# cask install
